CASE_TYPE_LEVEL_MAPPING = {
    'activate-sim' : [
        ['GHP_GLOBE POSTPAID','GRC_RECONTRACTING RELATED','OTHER RECONTRACTING RELATED CONCERN','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'prolonged-outage' : [
        ['WIRELINE_WIRELINE','WDR_DEVICE & NETWORK RELATED COMPLAINT','OUTAGE REPORT','NO CONNECTION','ENDORSED TO IROC']
    ],
    'load-promos-rewards' : [
        ['CXP-SELF-SERVICE','CONTACT GLOBE - OTHERS - PREPAID','REQUESTED VIA GSVC','N/A','N/A'],
        ['CXP-SELF-SERVICE','CONTACT GLOBE - OTHERS - TM','REQUESTED VIA GSVC','N/A','N/A'],
        ['GHP-PREPAID_GLOBE PREPAID','PPC_PROMO, PRODUCT&VAS RELATED COMPLAINT','OTHER PROMO & VAS COMPLAINT','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['TM_TM','TPC_PROMO, PRODUCT&VAS RELATED COMPLAINT','OTHER PROMO & VAS COMPLAINT','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['PW_GLOBE AT HOME PREPAID WIFI','PWS_SERVICE RELATED','TOP UP REQUEST','REVERSAL','ENDORSED TO SF FOR HANDLING'],
        ['CXP-SELF-SERVICE','CONTACT GLOBE - REWARD REDMPTION CONCERN','REQUESTED VIA GSVC','N/A','N/A'],
        ['GHP-PREPAID_GLOBE PREPAID','PSR_SERVICE RELATED','TOP UP REQUEST','REVERSAL','ENDORSED TO SF FOR HANDLING'],
        ['TM_TM','TSR_SERVICE RELATED','TOP UP REQUEST','REVERSAL','ENDORSED TO SF FOR HANDLING']
    ],
    'bill-dispute' : [
        ['WIRELINE_WIRELINE','WBC_BILLING RELATED COMPLAINT','BILLING CHARGES','DISPUTE ON CHARGES','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['WIRELINE_WIRELINE','WBR_BILLING RELATED REQUEST','PAYMENT RELATED','PAYMENT ARRANGEMENT_CONS','ENDORSED TO CREDIT FOR PROCESSING'],
        ['WIRELINE_WIRELINE','WBR_BILLING RELATED REQUEST','OTHER BILLING RELATED REQUEST','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['WIRELINE_WIRELINE','WBR_BILLING RELATED REQUEST','BILL DELIVERY','BILL RESEND REQUEST - CONSUMER','ENDORSED TO SUPPORT FOR PROCESSING'],
        ['GHP_GLOBE POSTPAID','GBC_BILLING RELATED COMPLAINT','BILLING CHARGES','DISPUTE ON CHARGES','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['GHP_GLOBE POSTPAID','GBR_BILLING RELATED REQUEST','PAYMENT RELATED','PAYMENT ARRANGEMENT','ENDORSED TO CREDIT FOR PROCESSING'],
        ['GHP_GLOBE POSTPAID','GBR_BILLING RELATED REQUEST','OTHER BILLING RELATED REQUEST','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['DCM_G1', 'GBC-BILLING RELATED COMPLAINT_POST', 'BILLING CHARGES', 'DISPUTE ON CHARGES', 'ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['DCM_G1', 'WBC-BILLING RELATED COMPLAINT_BBPOST','BILLING CHARGES','DISPUTE ON CHARGES', 'ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'reconnection' : [
        ['CXP-SELF-SERVICE','RESUME','REQUESTED VIA WEB','N/A','N/A'],
        ['WIRELINE_WIRELINE', 'WAO_OTHER ACCOUNT RELATED REQUESTS', 'OTHERS', 'OTHERS', 'ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['GHP_GLOBE POSTPAID', 'GAM_ACCOUNT RELATED MODIFICATION', 'ACCOUNT STATUS', 'RESUME REQUEST', 'ENDORSED TO SUPPORT GROUP FOR HANDLING'],
	    ['WIRELINE_WIRELINE', 'WAM_ACCOUNT RELATED MODIFICATION', 'ACCOUNT STATUS', 'RESUME REQUEST', 'ENDORSED TO SUPPORT GROUP FOR HANDLING']
        
    ],
    'new-reconnection' : [
        ['GHP_GLOBE POSTPAID', 'GAM_ACCOUNT RELATED MODIFICATION', 'ACCOUNT STATUS', 'RESUME REQUEST', 'ENDORSED TO SUPPORT GROUP FOR HANDLING'],
	    ['WIRELINE_WIRELINE', 'WAM_ACCOUNT RELATED MODIFICATION', 'ACCOUNT STATUS', 'RESUME REQUEST', 'ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'unposted-payment' : [
        ["WIRELINE_WIRELINE", "WBC_BILLING RELATED COMPLAINT", "PAYMENT RELATED", "UNPOSTED PAYMENT_CONS", "ENDORSED TO BILLING FOR PROCESSING"],
        ["GHP_GLOBE POSTPAID", "GBC_BILLING RELATED COMPLAINT", "PAYMENT RELATED", "UNPOSTED PAYMENT", "ENDORSED TO BILLING FOR PROCESSING"]
    ],
    'recon-td':[
        ["GHP_GLOBE POSTPAID", "GAM_ACCOUNT RELATED MODIFICATION", "ACCOUNT STATUS", "RESUME REQUEST", "ENDORSED TO SUPPORT GROUP FOR HANDLING"],
        ["WIRELINE_WIRELINE", "WAM_ACCOUNT RELATED MODIFICATION", "ACCOUNT STATUS", "RESUME REQUEST", "ENDORSED TO SUPPORT GROUP FOR HANDLING"],
    ],    
    'termination' : [
        ['CXP-SELF-SERVICE','DIRECT ASSIST','REQUESTED VIA GSVC','N/A','N/A'],
        ['WIRELINE_WIRELINE','WRR_RETENTION RELATED REQUEST','COST CUTTING','OFFER PLAN DOWNGRADE','ENDORSED TO OUTBOUND SAVE TEAM'],
        ['WIRELINE_WIRELINE','WRR_RETENTION RELATED REQUEST','CEASE REQUEST','SECOND LEVEL SAVE EFFORT','ENDORSED TO TL FOR HANDLING']
    ],
    'change-plan' : [
        ['CXP-SELF-SERVICE','CHANGE PLAN','REQUESTED VIA GSVC','N/A','N/A']
    ],
    'transfer-of-location' : [
        ['WIRELINE_WIRELINE','WAM_ACCOUNT RELATED MODIFICATION','ACCOUNT STATUS','TRANSFER OF LOCATION/MOVE','ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'bb-upgrade-plan' : [
        ['WIRELINE_WIRELINE','WAM_ACCOUNT RELATED MODIFICATION','OTHER ACCOUNT MODIFICATION CONCERN','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['WIRELINE_WIRELINE','WAM_ACCOUNT RELATED MODIFICATION','CHANGE PLAN','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['WIRELINE_WIRELINE','WAM_ACCOUNT RELATED MODIFICATION','MIGRATION','CHANGE IN TECHNOLOGY','ENDORSED TO SUPPORT GROUP FOR HANDLING'],
        ['WIRELINE_WIRELINE','WAM_ACCOUNT RELATED MODIFICATION','CHANGE PLAN','WITH UPSELL','ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'call-and-text' : [
        ['CXP-SELF-SERVICE','CONTACT GLOBE - SIGNAL CONCERNS','REQUESTED VIA GSVC','N/A','N/A']
    ],
    'check-application' : [
        ['GHP_GLOBE POSTPAID','GRC_RECONTRACTING RELATED','OTHER RECONTRACTING RELATED CONCERN','OTHERS','ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    'open-order' : [
        ['WIRELINE_WIRELINE','WDR_DEVICE & NETWORK RELATED COMPLAINT','REPAIR','OTHERS','ENDORSED TO IROC']
    ],
    'unlock-device-prepaid': [
        ['GHP-PREPAID_GLOBE PREPAID', 'PHR_HANDSET & DEVICE RELATED', 'HANDSET & DEVICE CONCERN', 'HANDSET UNLOCKING', 'ENDORSED TO SF FOR HANDLING']
    ],
    'gofam-load-promos-rewards' : [
        ['GHP-PREPAID_GLOBE PREPAID', 'PSR_SERVICE RELATED', 'TOP UP REQUEST', 'REVERSAL', 'ENDORSED TO SF FOR HANDLING'],
        ['GHP-PREPAID_GLOBE PREPAID', 'PLC_LOAD UP RELATED CONCERN', 'LOAD UP COMPLAINT', 'NON-RECEIPT OF LOAD', 'ENDORSED TO BIZ PREPAID SUPPORT'],
        ['GHP-PREPAID_GLOBE PREPAID', 'PSC_SERVICE RELATED CONCERN', 'PROMO / FREEBIE', 'UNABLE TO USE AVAILED SERVICE', 'ENDORSED TO ISG FOR HANDLING'],
        ['GHP-PREPAID_GLOBE PREPAID', 'PRW_REWARDS RELATED', 'OTHER REWARDS RELATED CONCERN', 'OTHERS', 'ENDORSED TO SUPPORT GROUP FOR HANDLING']
    ],
    "thea-get-globe-at-home": [
        ["APPLICATION PROCESS", "AAV_VERIFICATION", "ADDITIONAL ACCOUNT", "BROADBAND", "ENDORSED TO OM"]
    ],
    'bb-network-concern': [
        ["TT_TROUBLE TICKET", "WTB-VOICE AND DATA RELATED", "NO VOICE NO DATA", "NO INTERNET NO DIAL TONE", "ENDORSED TO CFS"],
        ["TT_TROUBLE TICKET", "WTC_CONNECTION RELATED", "SLOW BROWSING", "ACROSS ALL SITES", "ENDORSED TO CFS"],
        ["TT_TROUBLE TICKET", "WTV_VOICE RELATED", "NO DIAL / BUSY TONE", "UPON HANDSET PICK  UP", "ENDORSED TO CFS"]
    ],
    'overdue-balance-reconnection': [
        ["GAM_ACCOUNT RELATED MODIFICATION", "ACCOUNT STATUS", "RESUME REQUEST", "ENDORSED TO SUPPORT GROUP FOR HANDLING"],
        ["WAM_ACCOUNT RELATED MODIFICATION", "ACCOUNT STATUS", "RESUME REQUEST", "ENDORSED TO SUPPORT GROUP FOR HANDLING"] 
    ]
}
