case_tags = {
    'unlock-device-postpaid':{
        'title': 'SNS_Unlocking', #from 'Consumer_HANDSET & DEVICE CONCERN'/
        'queue': 'TP SF WIRELESS', # from "RPA_UNLOCK_PHONE" / replaced (CCM FEEDBACK WIRELESS) / returned to "RPA_UNLOCK_PHONE"/From "RPA_UNLOCK_PHONE"
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'DIRECT ASSIST',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'Unlock device',
        'sla' : '5-10 days'
    },
    'unlock-device-prepaid':{
        'title'     : 'PREPAID: UNLOCKING REQ_ELIGIBLE-NOT UNLOCKED',
        'queue'     : 'TP SF WIRELESS', # from "RPA_UNLOCK_PHONE" / replaced (CCM FEEDBACK WIRELESS) / returned to "RPA_UNLOCK_PHONE"/From "RPA_UNLOCK_PHONE"
        'lvl1'      : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2'      : 'PHR_HANDSET & DEVICE RELATED',
        'lvl3'      : 'HANDSET & DEVICE CONCERN',
        'lvl4'      : 'HANDSET UNLOCKING',
        'lvl5'      : 'ENDORSED TO SF FOR HANDLING',
        'reason'    : 'Unlock device',
        'sla'       : '3 business days'
    },
    'unlock-device-tm':{
        'title': 'SNS_Unlocking_TM', # from 'Consumer_HANDSET & DEVICE CONCERN'
        'queue': 'TP SF WIRELESS', # from "RPA_UNLOCK_PHONE" / replaced (CCM FEEDBACK WIRELESS) / returned to "RPA_UNLOCK_PHONE" /From "RPA_UNLOCK_PHONE"
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'DIRECT ASSIST',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'Unlock device',
        'sla' : '3 business days'
    },
    'bill-dispute-postpaid':{
        'title': 'SNS_Bill Dispute',
        'queue': 'TP Wireless Tier2', # any of ['RPA BILL DISPUTE','TP Wireless Tier2','TMD Wireless SNS Bill Dispute'] 
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GBC_BILLING RELATED COMPLAINT',
        'lvl3' : 'BILLING CHARGES',
        'lvl4' : 'DISPUTE ON CHARGES',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'bill-dispute-recontracting-postpaid':{
        'title': 'SNS_Bill Dispute',
        'queue': 'TP Wireless Tier2', # any of ['RPA BILL DISPUTE','TP Wireless Tier2','TMD Wireless SNS Bill Dispute'] 
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GBC_BILLING RELATED COMPLAINT',
        'lvl3' : 'BILLING CHARGES',
        'lvl4' : 'DISPUTE ON CHARGES',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'bill-dispute-ipp-postpaid':{
        'title': 'SNS_IPP Enrollment',
        'queue': 'CREDIT CONSUMER MOBILE',
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GBR_BILLING RELATED REQUEST',
        'lvl3' : 'PAYMENT RELATED',
        'lvl4' : 'PAYMENT ARRANGEMENT',
        'lvl5' : 'ENDORSED TO CREDIT FOR PROCESSING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'bill-dispute-financial-care-postpaid':{
        'title': 'SNS_Globe Care Program',
        'queue': 'RETENTION WLESS ADMIN',
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GBR_BILLING RELATED REQUEST',
        'lvl3' : 'OTHER BILLING RELATED REQUEST',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'bill-dispute-ipp-bb':{
        'title': 'SNS_BB IPP Enrollment',
        'queue': 'Credit Consumer Wireline',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WBR_BILLING RELATED REQUEST',
        'lvl3' : 'PAYMENT RELATED',
        'lvl4' : 'PAYMENT ARRANGEMENT_CONS',
        'lvl5' : 'ENDORSED TO CREDIT FOR PROCESSING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'bill-dispute-financial-care-bb':{
        'title': 'SNS_BB Financial Care Program',
        'queue': 'WLINE RETENTION TL',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WBR_BILLING RELATED REQUEST',
        'lvl3' : 'OTHER BILLING RELATED REQUEST',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'slow-or-no-internet-ntg-postpaid':{
    'title': 'SNS_Network Related_Post_Slow/No Internet',
    'queue': 'NTG-SD_WLESS_POSTPAID',
    'lvl1' : 'CXP-SELF-SERVICE',
    'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
    'lvl3' : 'REQUESTED VIA GSVC',
    'lvl4' : 'N/A',
    'lvl5' : 'N/A',
    'reason' : 'networkIssue',
    'sla' : '48 hours'
    },
    'slow-or-no-internet-ntg-prepaid':{
        'title': 'SNS_Network Related_Pre_Slow/No Internet',
        'queue': 'NTG-SD_WLESS_PREPAID',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'networkIssue',
        'sla' : '48 hours'
    },
    'slow-or-no-internet-ntg-tm':{
        'title': 'SNS_Network Related_TM_Slow/No Internet',
        'queue': 'NTG-SD_WLESS_TM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'networkIssue',
        'sla' : '48 hours'
    },
    'call-and-text-ntg-postpaid':{
        'title': 'SNS_Network Related_Post_Call/SMS',
        'queue': 'NTG-SD_WLESS_POSTPAID',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'call-and-text-ntg-prepaid':{
        'title': 'SNS_Network Related_Pre_Call/SMS',
        'queue': 'NTG-SD_WLESS_PREPAID',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'call-and-text-ntg-tm':{
        'title': 'SNS_Network Related_TM_Call/SMS',
        'queue': 'NTG-SD_WLESS_TM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'slow-or-no-internet-postpaid':{
        'title': 'SNS_Network Related_Post_Slow/No Internet',
        'queue': 'TP SNS Postpaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'networkIssue',
        'sla' : '48 hours'
    },
    'slow-or-no-internet-prepaid':{
        'title': 'SNS_Network Related_Pre_Slow/No Internet',
        'queue': 'TP SNS Prepaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'networkIssue',
        'sla' : '48 hours'
    },
    'slow-or-no-internet-tm':{
        'title': 'SNS_Network Related_TM_Slow/No Internet',
        'queue': 'TP SNS Prepaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'networkIssue',
        'sla' : '48 hours'
    },
    'call-and-text-postpaid':{
        'title': 'SNS_Network Related_Post_Call/SMS',
        'queue': 'TP SNS Postpaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'call-and-text-prepaid':{
        'title': 'SNS_Network Related_Pre_Call/SMS',
        'queue': 'TP SNS Prepaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'call-and-text-tm':{
        'title': 'SNS_Network Related_TM_Call/SMS',
        'queue': 'TP SNS Prepaid Network',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - SIGNAL CONCERNS',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : '',
        'sla' : '48 hours'
    },
    'bill-dispute-broadband':{
        'title': 'BB_SNS_BILL DISPUTE',
        'queue': 'CNX Wireline Tier2', 
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WBC_BILLING RELATED COMPLAINT',
        'lvl3' : 'BILLING CHARGES',
        'lvl4' : 'DISPUTE ON CHARGES',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'lpr-load-deduction-prepaid-ghp':{
        'title': 'SNS_Load Deduction Concern',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-load-deduction-tm':{
        'title': 'SNS_Load Deduction Concern',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-load-deduction-prepaid-reversal':{
        'title': 'Auto_SNS_Load Deduction Concern',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-load-deduction-tm-reversal':{
        'title': 'Auto_SNS_Load Deduction Concern',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'TM_TM',
        'lvl2' : 'TSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-load-prepaid-ghp':{
        'title': "SNS_Didn't Receive Load",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-load-tm':{
        'title': "SNS_TM_Didn't Receive Load",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-load-prepaid-reversal':{
        'title': "Auto_SNS_Didn't Receive Load",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-load-tm-reversal':{
        'title': "Auto_SNS_Didn't Receive Load",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'TM_TM',
        'lvl2' : 'TSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-loan-utang-load-prepaid-ghp':{
        'title': 'SNS_Prepaid_Loan Load',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-loan-utang-load-tm':{
        'title': 'SNS_TM_Utang Load',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cannot-share-prepaid-ghp':{
        'title': 'TBD',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cannot-share-tm':{
        'title': 'TBD',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-sal-prepaid-ghp':{
        'title': 'SNS_Prepaid_SAL_SAP',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-sal-tm':{
        'title': 'SNS_TM_SAL_SAP',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-sent-to-wrong-number-all-lob':{
        'title': 'TBD',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-prepaid-ghp':{
        'title': "SNS_Prepaid_Didn't Receive Promo",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PPC_PROMO, PRODUCT&VAS RELATED COMPLAINT',
        'lvl3' : 'OTHER PROMO & VAS COMPLAINT',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-tm':{
        'title': "SNS_TM_Didn't Receive Promo",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'TM_TM',
        'lvl2' : 'TPC_PROMO, PRODUCT&VAS RELATED COMPLAINT',
        'lvl3' : 'OTHER PROMO & VAS COMPLAINT',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-hpw':{
        'title': 'SNS_REVERSAL FOR PREPAID HOME WIFI HPW',
        'queue': 'CCM PTI CCO-AMAX',
        'lvl1' : 'PW_GLOBE AT HOME PREPAID WIFI',
        'lvl2' : 'PWS_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-prepaid-reversal':{
        'title': "SNS_Auto_Didn't Receive Promo",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-tm-reversal':{
        'title': "SNS_Auto_Didn't Receive Promo",
        'queue': 'PTA SNS TechM',
        'lvl1' : 'TM_TM',
        'lvl2' : 'TSR_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-promo-hpw-reversal':{
        'title': "SNS_Auto_Didn't Receive Promo",
        'queue': 'CCM PTI CCO-AMAX',
        'lvl1' : 'PW_GLOBE AT HOME PREPAID WIFI',
        'lvl2' : 'PWS_SERVICE RELATED',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : 'ENDORSED TO SF FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-data-consumed-faster-all-lob':{
        'title': 'TBD',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-sap-prepaid-ghp':{
        'title': 'SNS_Prepaid_SAL_SAP',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - PREPAID',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-sap-tm':{
        'title': 'SNS_TM_SAL_SAP',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - OTHERS - TM',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cant-redeem-prepaid-ghp':{
        'title': 'SNS_Prepaid Rewards_Cant Redeem',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cant-redeem-tm':{
        'title': 'SNS_TM Rewards_Cant Redeem',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cant-redeem-postpaid':{
        'title': 'SNS_Postpaid Rewards',
        'queue': 'CNX Wireless Tier2',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-cant-redeem-broadband':{
        'title': "BB PROMO RELATED CONCERN_CAN'T REDEEM",
        'queue': 'CNX Wireline Chat2Call',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WSC_SERVICE RELATED CONCERN',
        'lvl3' : 'PROMO / FREEBIE',
        'lvl4' : 'UNABLE TO USE AVAILED SERVICE',
        'lvl5' : 'ENDORSED TO ISG FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-reward-points-broadband':{
        'title': "BB PROMO RELATED CONCERN_DIDN'T RECEIVE REWARDS POINTS",
        'queue': 'CNX Wireline Chat2Call',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WSC_SERVICE RELATED CONCERN',
        'lvl3' : 'PROMO / FREEBIE',
        'lvl4' : 'UNABLE TO USE AVAILED SERVICE',
        'lvl5' : 'ENDORSED TO ISG FOR HANDLING',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-reward-points-prepaid-ghp':{
        'title': 'SNS_Prepaid Rewards_Did not receive rewards',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-reward-points-tm':{
        'title': 'SNS_TM Rewards_Did not receive rewards',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-did-not-receive-reward-points-postpaid':{
        'title': 'SNS_Postpaid Rewards',
        'queue': 'CNX Wireless Tier2',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'lpr-puk-all-lob':{
        'title': 'TBD',
        'queue': 'PTA SNS TechM',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CONTACT GLOBE - REWARD REDMPTION CONCERN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'load, promos, and rewards',
        'sla' : '48 hours'
    },
    'modify-or-terminate-postpaid':{
        'title': 'SNS_Termination Request',
        'queue': 'RETENTION WLESS ADMIN', # changed from RETENTION WLESS TP (Sprint 94)
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'DIRECT ASSIST',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'termination',
        'sla' : '5 business days'
    },
    'modify-or-terminate-broadband':{
        'title': 'BB_SNS_Termination Request',
        'queue': 'WLINE RETENTION TL', # changed from RETENTION WLESS TP (Sprint 94)
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'DIRECT ASSIST',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'termination',
        'sla' : '5 business days'
    },
    'transfer-of-location-broadband':{
        'title': 'SNS_CUSTOMER INITIATED-TOL REQUEST',
        'queue': 'CCM FEEDBACK WIRELINE', # reverted from CCM IVR RECON CSR PTI
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'ACCOUNT STATUS',
        'lvl4' : 'TRANSFER OF LOCATION/MOVE',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'transfer of location',
        'sla' : ''
    },
    'transfer-of-location-bb-non-serviceable':{
        'title': 'FBM TOL REQUEST NOT SERVICEABLE',
        'queue': 'CCM FEEDBACK WIRELINE',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'ACCOUNT STATUS',
        'lvl4' : 'TRANSFER OF LOCATION/MOVE',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'transfer of location',
        'sla' : '48 hours'
    },
    'modify-or-terminate-change-plan-postpaid':{
        'title': 'SNS_Change Plan',
        'queue': 'TP Wireless Tier2',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'CHANGE PLAN',
        'lvl3' : 'REQUESTED VIA GSVC',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'changePlan',
        'sla' : '48 hours'
    },
    'modify-or-terminate-mnp-postpaid':{
        'title': 'SNS_MNP POST TO PRE REQUEST',
        'queue': 'RETENTION WLESS ADMIN',
        'lvl1' : 'CXP-SELF-SERVICE',
        'lvl2' : 'DIRECT ASSIST',
        'lvl3' : 'REQUESTED VIA WEB',
        'lvl4' : 'N/A',
        'lvl5' : 'N/A',
        'reason' : 'number porting',
        'sla' : '3 days'
    },
    'modify-or-terminate-bb-termination':{
        'title': 'FBM BB TERMINATION REQUEST',
        'queue': 'WLINE RETENTION TL',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WRR_RETENTION RELATED REQUEST',
        'lvl3' : 'CEASE REQUEST',
        'lvl4' : 'SECOND LEVEL SAVE EFFORT',
        'lvl5' : 'ENDORSED TO TL FOR HANDLING',
        'reason' : 'termination',
        'sla' : '24 hours'
    },
    'modify-or-terminate-bb-retention':{
        'title': 'FBM BB TERMINATION REQUEST',
        'queue': 'WLINE RETENTION TL',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WRR_RETENTION RELATED REQUEST',
        'lvl3' : 'COST CUTTING',
        'lvl4' : 'OFFER PLAN DOWNGRADE',
        'lvl5' : 'ENDORSED TO OUTBOUND SAVE TEAM',
        'reason' : 'termination',
        'sla' : '24 hours'
    },
    'followup-concern-vip-user':{
        'title': 'Socio VIP_Follow_up Concern',
        'queue': 'CCM SNS HEAD',
        'lvl1' : 'ALL_GLOBAL TAGS',
        'lvl2' : 'IGZ_GENERIC CONCERN',
        'lvl3' : 'ESCALATION CONCERN',
        'lvl4' : 'FOR CASE CREATION',
        'lvl5' : 'ENDORSED FOR HANDLING',
        'reason' : '',
        'sla' : ''
    },
    'bb-upgrade-plan':{
        'title': 'FELICITY_PLAN UPGRADE_FBM',
        'queue': 'TECHM UPSELL FFILLMENT',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'OTHER ACCOUNT MODIFICATION CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 HRS'
    },
    'bb-upgrade-plan-other-plan':{
        'title': 'FBM PLAN UPGRADE REQUEST PART OF WLIST',
        'queue': 'TECHM UPSELL FFILLMENT',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'CHANGE PLAN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '24 HRS'
    },
    'bb-downgrade-plan':{
        'title': 'FBM PLAN DOWNGRADE REQUEST CUSTOMER INITIATED',
        'queue': 'CNX BB RECONTRACTING',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'CHANGE PLAN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '24 HRS'
    },
    'bb-upgrade-plan-not-wl':{
        'title': 'FBM PLAN UPGRADE REQUEST CUSTOMER INITIATED',
        'queue': 'CNX BB RECONTRACTING',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'CHANGE PLAN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '24 HRS'
    },
    'bb-upgrade-plan-not-wl-non-gpon':{
        'title': 'FBM PLAN UPGRADE WITH CHANGE TECH REQUEST CUSTOMER INITIATED',
        'queue': 'BB MIGRATION FEEDBACK',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WAM_ACCOUNT RELATED MODIFICATION',
        'lvl3' : 'MIGRATION',
        'lvl4' : 'CHANGE IN TECHNOLOGY',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 HRS'
    },
    'bb-prolonged-outage':{
        'title': 'PART OF PROLONG OUTAGE',
        'queue': 'CARE_MANAGER_TM',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WDR_DEVICE & NETWORK RELATED COMPLAINT',
        'lvl3' : 'OUTAGE REPORT',
        'lvl4' : 'NO CONNECTION',
        'lvl5' : 'ENDORSED TO IROC',
        'reason' : '',
        'sla' : '48 HRS'
    },
    'stuck-pending-order':{
        'title': 'PART OF STUCK ORDER FOR MONITORING',
        'queue': 'CARE_MANAGER_ABSI',
        'lvl1' : 'ALL_GLOBAL TAGS',
        'lvl2' : 'IGZ_GENERIC CONCERN',
        'lvl3' : 'OTHER GENERIC CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'pending order',
        'sla' : '3 days'        
    },
    'thea-platinum-upgrade-offer1-upgrade':{
        'title': 'Thea Upselling_Upgrade Request',
        'queue': 'THEA LOYALTY QA',
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GAC_ACCOUNT RELATED CONCERN',
        'lvl3' : 'PLATINUM ACCOUNT CONCERN',
        'lvl4' : 'REQUEST FOR CALLBACK',
        'lvl5' : 'ENDORSED TO PLATINUM RM FOR HANDLING',
        'reason' : 'platinum upgrade',
        'sla' : '2-3 days'
    },
    'thea-platinum-upgrade-offer1-discussmore':{
        'title': 'Thea Upselling_Discuss More',
        'queue': 'CS PAM SUPPORT',
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GAC_ACCOUNT RELATED CONCERN',
        'lvl3' : 'PLATINUM ACCOUNT CONCERN',
        'lvl4' : 'REQUEST FOR CALLBACK',
        'lvl5' : 'ENDORSED TO PLATINUM RM FOR HANDLING',
        'reason' : 'platinum upgrade',
        'sla' : '2-3 days'
    },
    'bb-onsite-visit-chat':{
        'title': 'SNS_OFU RELATED CHAT RQST',
        'queue': 'DNA AMBASSADOR TL',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WDR_DEVICE & NETWORK RELATED COMPLAINT',
        'lvl3' : 'OTHER DEVICE OR NETWORK COMPLAINT',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'Onsite Visit',
        'sla' : ''
    },
    'bb-onsite-visit-call':{
        'title': 'FBM_OFU RELATED CALL RQST',
        'queue': 'DNA AMBASSADOR TL',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WDR_DEVICE & NETWORK RELATED COMPLAINT',
        'lvl3' : 'OTHER DEVICE OR NETWORK COMPLAINT',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'Onsite Visit',
        'sla' : ''
    },
    'bb-cant-connect-to-internet':{
        'title': 'FBM_FOR ONSITE REPAIR_<NO INTERNET NO DIAL TONE>',
        'queue': 'Wireline IROC CFT',
        'lvl1' : 'TT_TROUBLE TICKET',
        'lvl2' : 'WTB-VOICE AND DATA RELATED',
        'lvl3' : 'NO VOICE NO DATA',
        'lvl4' : 'NO INTERNET NO DIAL TONE',
        'lvl5' : 'ENDORSED TO CFS',
        'reason' : 'Onsite Visit',
        'sla' : ''
    },
    'bb-cant-use-my-telephone':{
        'title': 'FBM_FOR ONSITE REPAIR_<UPON HANDSET PICK UP>',
        'queue': 'Wireline IROC CFT',
        'lvl1' : 'TT_TROUBLE TICKET',
        'lvl2' : 'WTV_VOICE RELATED',
        'lvl3' : 'NO DIAL / BUSY TONE',
        'lvl4' : 'UPON HANDSET PICK  UP',
        'lvl5' : 'ENDORSED TO CFS',
        'reason' : 'Onsite Visit',
        'sla' : ''
    },
    'bb-slow-internet-connection':{
        'title': 'FBM_FOR ONSITE REPAIR_ACROSS ALL SITES',
        'queue': 'Wireline IROC CFT',
        'lvl1' : 'TT_TROUBLE TICKET',
        'lvl2' : 'WTC_CONNECTION RELATED',
        'lvl3' : 'SLOW BROWSING',
        'lvl4' : 'ACROSS ALL SITES',
        'lvl5' : 'ENDORSED TO CFS',
        'reason' : 'Onsite Visit',
        'sla' : ''
    },
    'bb-open-order':{
        'title': 'FBM_FOR ONSITE REPAIR_ WITH OPEN ORDER',
        'queue': 'TP Wireline Tier2',
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WDR_DEVICE & NETWORK RELATED COMPLAINT',
        'lvl3' : 'REPAIR',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO IROC',
        'reason' : 'Onsite Visit',
        'sla' : '24 hours'
    },
    'bill-dispute-unreceived-broadband':{
        'title': 'SNS_BB BILL VIA EMAIL RESEND',
        'queue': 'CCM FULFILLMENT WIRELINE', 
        'lvl1' : 'WIRELINE_WIRELINE',
        'lvl2' : 'WBR_BILLING RELATED REQUEST',
        'lvl3' : 'BILL DELIVERY',
        'lvl4' : 'BILL RESEND REQUEST - CONSUMER',
        'lvl5' : 'ENDORSED TO SUPPORT FOR PROCESSING',
        'reason' : 'billing',
        'sla' : '48 hours'
    },
    'sim-reg-globe-prepaid':{
        'title': 'SNS_SIM CARD REGISTRATION UNBARRING',
        'queue': 'PTA SNS TechM', # from 'NIA SERVICE RECOVERY',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PAC_ACCOUNT RELATED CONCERN',
        'lvl3' : 'OTHER ACCOUNT RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 hours'
    },
    'sim-reg-tm':{
        'title': 'SNS_SIM CARD REGISTRATION UNBARRING',
        'queue': 'PTA SNS TechM', # from 'NIA SERVICE RECOVERY',
        'lvl1' : 'TM_TM',
        'lvl2' : 'TSC_SERVICE RELATED CONCERN',
        'lvl3' : 'OTHER SERVICE RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 hours'
    },
    'sim-reg-gah-hpw':{
        'title': 'SNS_SIM CARD REGISTRATION UNBARRING',
        'queue': 'PTA SNS TechM', # from 'NIA SERVICE RECOVERY',
        'lvl1' : 'PW_GLOBE AT HOME PREPAID WIFI',
        'lvl2' : 'PWS_SERVICE RELATED',
        'lvl3' : 'OTHER SERVICE RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 hours'
    },
    'proactive-renewal':{
        'title': 'THEA RENEWAL REQUEST',
        'queue': 'THEA LOYALTY QA',
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GRC_RECONTRACTING RELATED',
        'lvl3' : 'ELIGIBILITY',
        'lvl4' : 'LINE ONLY',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '48 hours'
    },
    'check-application-renewal-online':{
        'title': 'LEX_Renewal Online',
        'queue': 'CBS QA', #Care Team CNX Shaw
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GRC_RECONTRACTING RELATED',
        'lvl3' : 'OTHER RECONTRACTING RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'check application',
        'sla' : '48 hours'
    },
    'check-application-renewal-store-gle':{
        'title': 'LEX_Renewal Easy Hub',
        'queue': 'CBS QA', #Care Team CNX Shaw
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GRC_RECONTRACTING RELATED',
        'lvl3' : 'OTHER RECONTRACTING RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'check application',
        'sla' : '48 hours'
    },
    'check-application-renewal-store-no-gle':{
        'title': 'LEX_Renewal Globe Stores',
        'queue': 'GOTS Recon Verif', #'Care Team TechM', # (RITM0894720) from 'CBS Sales Ordering' #Care Team Mkt
        'lvl1' : 'GHP_GLOBE POSTPAID',
        'lvl2' : 'GRC_RECONTRACTING RELATED',
        'lvl3' : 'OTHER RECONTRACTING RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : 'check application',
        'sla' : '48 hours'
    },
    'lpr-gofam-load-concern':{
        'title': 'GLOBE REWARDS+ LOAD CONCERN',
        'queue': 'CCM Prepaid TL',
        'lvl1' : 'DCM_FBM',
        'lvl2' : 'PSR-SERVICE RELATED_PREP',
        'lvl3' : 'TOP UP REQUEST',
        'lvl4' : 'REVERSAL',
        'lvl5' : ' ENDORSED TO SF FOR HANDLING',
        'reason' : '',
        'sla' : '12 hours'
    },
    'lpr-gofam-loan-concern':{
        'title': 'GLOBE REWARDS+ LOAN CONCERN',
        'queue': 'CCM Prepaid TL',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PLC_LOAD UP RELATED CONCERN',
        'lvl3' : 'LOAD UP COMPLAINT',
        'lvl4' : 'NON-RECEIPT OF LOAD',
        'lvl5' : 'ENDORSED TO BIZ PREPAID SUPPORT',
        'reason' : '',
        'sla' : '12 hours'
    },
    'lpr-gofam-promo-concern':{
        'title': 'GLOBE REWARDS+ PROMO CONCERN',
        'queue': 'CCM Prepaid TL',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PSC_SERVICE RELATED CONCERN',
        'lvl3' : 'PROMO / FREEBIE',
        'lvl4' : 'UNABLE TO USE AVAILED SERVICE',
        'lvl5' : 'ENDORSED TO ISG FOR HANDLING',
        'reason' : '',
        'sla' : '12 hours'
    },
    'lpr-gofam-rewards-concern':{
        'title': 'GLOBE REWARDS+ CONCERN',
        'queue': 'CCM Prepaid TL',
        'lvl1' : 'GHP-PREPAID_GLOBE PREPAID',
        'lvl2' : 'PRW_REWARDS RELATED',
        'lvl3' : 'OTHER REWARDS RELATED CONCERN',
        'lvl4' : 'OTHERS',
        'lvl5' : 'ENDORSED TO SUPPORT GROUP FOR HANDLING',
        'reason' : '',
        'sla' : '12 hours'
    }
}