MENU_RENEW_PLAN = "[menu].renewmyplan"
MENU_RENEW_PLAN_RESERVE_NOW = "[menu].getiphone13reservenow"
MENU_RENEW_PLAN_CHECK_STATUS = "[menu].getiphone13checkstatus"
MENU_RENEW_PLAN_CHECK_ELIGIBILITY = "[menu].renewplancheckeligibility"
MENU_RENEW_PLAN_VISIT_ONLINE_SHOP = "[menu].renewplanvisitonlineshop"
MENU_RENEW_PLAN_REPORT_ONLINE_ISSUE = "[menu].reportissueonlineissue"
MENU_RENEW_PLAN_FOLLOWUP_ORDER = "[menu].reportissuefollowuporder"
MENU_BB_UPSELL_OFFER_1 = "[menu].getbbupselloffer1"
MENU_BB_UPSELL_OFFER_2 = "[menu].getbbupselloffer2"
MENU_BB_UPSELL_OFFER_3 = "[menu].getbbupselloffer3"
MENU_BB_UPSELL_OFFER_GENERIC = "[menu].getbbupsellgeneric"
MENU_NETWORK_CONCERN_DATE_ENCOUNTERED_TODAY = "[menu].todayMenu"
MENU_NETWORK_CONCERN_DATE_ENCOUNTERED_YESTERDAY = "[menu].yesterdayMenu"
MENU_NETWORK_CONCERN_DATE_ENCOUNTERED_OTHER_DAY= "[menu].otherDayMenu"

MENU_FRAUD_REPORT_ILLEGAL_REPEATERS = "[menu].reportillegalrepeaters"
MENU_FRAUD_REPORT_FAKE_BILL_DISCOUNT = "[menu].reportfakebilldiscount"
MENU_FRAUD_REPORT_PROMO_TRICKS = "[menu].reportpromotricks"
MENU_FRAUD_REPORT_ILLEGAL_SELLING = "[menu].reportillegalselling"
MENU_FRAUD_REPORT_UNLI_FREE_DATA = "[menu].reportunlifreedata"
MENU_FRAUD_REPORT_OTHER_ONLINE_FRAUD = "[menu].reportotheronlinefraud"

#Globe One Concerns
MENU_GLOBE_ONE_CONCERN_APP_EXP = "[menu].appexperience"
MENU_GLOBE_ONE_CONCERN_PROMO_LOAD_PAYMENT_CONCERN = "[menu].gonepromoloadpaymentconcerns"
MENU_GLOBE_ONE_LOGIN_REGISTRATION_ISSUES = "[menu].loginregissues"
MENU_GLOBE_ONE_SLOW_APP_CRASH = "[menu].slowloadingappcrash"
MENU_GLOBE_ONE_CANNOT_PAY_BILL = "[menu].cannotpaymybill"
MENU_GLOBE_ONE_CANNOT_VIEW_BILL = "[menu].cannotviewmybill"
MENU_GLOBE_ONE_PAYMENT_DID_NOT_REFLECT = "[menu].paymentnotreflected"
MENU_GLOBE_ONE_CANNOT_BUY_LOAD_PROMO = "[menu].cannotbuyloadpromo"
MENU_GLOBE_ONE_DID_NOT_RECIEVE_LOAD_PROMO = "[menu].didnotrecieveloadpromo"
MENU_GLOBE_ONE_CANNOT_ADD_MOBILE_BB_NUM = "[menu].cannotaddmobilebbnum"
MENU_GLOBE_ONE_CANNOT_RECIEVE_OTP = "[menu].cannotrecieveotp"
MENU_GLOBE_ONE_CANNOT_REG_OR_LOGIN = "[menu].cannotregorlogin"
MENU_GLOBE_ONE_PAYMENT_DECLINED = "[menu].gonepaymentdeclined"
MENU_GLOBE_ONE_ERROR_OCCURRED = "[menu].gonesorryerroroccurred"
MENU_GLOBE_ONE_CANT_REG_PROMO = "[menu].gonenotabletoregisterpromo"
MENU_GLOBE_ONE_LOGIN_EMAIL = "[menu].goneloginemail"
MENU_GLOBE_ONE_FACEBOOK_EMAIL = "[menu].goneloginfacebook"
MENU_GLOBE_ONE_GMAIL_EMAIL = "[menu].gonelogingmail"
MENU_GLOBE_ONE_YAHOO_EMAIL = "[menu].goneloginyahoo"
MENU_GLOBE_ONE_APPLE_ACCOUNT_EMAIL = "[menu].goneloginappleaccount"
MENU_GLOBE_ONE_ISSUE_BUY_LOAD_PROMO = "[menu].buyloadpromo"
MENU_GLOBE_ONE_ISSUE_MODIFY_ACCOUNT = "[menu].modifyaccount"
MENU_GLOBE_ONE_ISSUE_VIEW_ACCOUNT_DETAILS = "[menu].viewaccountdetails"
MENU_GLOBE_ONE_ISSUE_REDEEM_REWARDS = "[menu].redeemrewards"
MENU_GLOBE_ONE_ISSUE_RAISE_CONCERN = "[menu].raiseaconcern"
MENU_GLOBE_ONE_ISSUE_PAY_BILL = "[menu].paybill"
MENU_GLOBE_ONE_WHATS_NEW = "[menu].whatsnewwithglobeone"
MENU_GLOBE_ONE_BROADBAND_ACCOUNT = "[menu].gonebroadband"
MENU_GLOBE_ONE_HPW_ACCOUNT = "[menu].gonehpw"
MENU_GLOBE_ONE_PREPAID_ACCOUNT = "[menu].gonemobileprepaid"
MENU_GLOBE_ONE_POSTPAID_ACCOUNT= "[menu].gonemobilepostpaid"
MENU_GLOBE_ONE_PAGE_NOT_LOADING_OPTION = "[menu].pagenotloading"
MENU_GLOBE_ONE_SOMETHING_WENT_WRONG_OPTION = "[menu].somethingwentwrongerror"
MENU_GLOBE_ONE_CANT_ADD_NUM_NEXT_STEP = "[menu].cannotaddaccountokay"

#Bills and Payments
MENU_HOW_TO_READ_MY_BILL = "[menu].howtoreadmybill"
MENU_IM_A_NEW_CUSTOMER = "[menu].imanewcustomer"
MENU_CHECK_REMANING_BALANCE = "[menu].checkremainingbalance"
MENU_UPGRADED_TO_FIBER = "[menu].upgradedtofiber"
MENU_MY_SPEED_WAS_UPGRADED = "[menu].speedwasupgraded"
MENU_SEE_AVAILED_DEVICES = "[menu].seeavaileddeviceequipment"

MENU_RECON_PAYMENT_NOT_REFLECTED                    = "[menu].reconpymtnotreflected"
MENU_RECON_ISSUE_WITH_MY_BILL                       = "[menu].reconissuewithmybill"
MENU_RECON_ISSUE_WITH_MY_PYMT_CHANNEL               = "[menu].reconissuewithmypymtchannel"
MENU_RECON_PYMT_NOT_REFLECTED_CHANNEL_GLOBE_APPS    = "[menu].reconglobeappschannel"
MENU_RECON_PYMT_NOT_REFLECTED_CHANNEL_BANKS         = "[menu].reconbankschannel"
MENU_RECON_PYMT_NOT_REFLECTED_CHANNEL_OTHERS        = "[menu].reconotherschannel"

MENU_UNLOCK_DEVICE_PHONE_BRAND_SAMSUNG              = "[menu].unlockdevicephonebrandsamsung"
MENU_UNLOCK_DEVICE_PHONE_BRAND_APPLE                = "[menu].unlockdevicephonebrandapple"
MENU_UNLOCK_DEVICE_PHONE_BRAND_OTHERS               = "[menu].unlockdevicephonebrandothers"

#Modify or Terminate
MENU_BB_CANCEL_FINANCIAL_CONCERNS                   = "[menu].cancelfinancialconcernsbb"
MENU_BB_CANCEL_SWITCHING_COMPETITOR                 = "[menu].cancelswitchingcompetitorbb"
MENU_BB_CANCEL_CONNECTION_ISSUES                    = "[menu].cancelconnectionissuesbb"
MENU_BB_CANCEL_TRANSFERRING_LOCATION                = "[menu].canceltransferringlocationbb"
MENU_BB_CANCEL_OTHERS                               = "[menu].cancelothersbb"
MENU_BB_CANCELLATION_EXPLORE_PLANS                  = "[menu].cancellationexploreplans"
MENU_BB_CANCELLATION_TROUBLESHOOT_CONNECTION        = "[menu].cancellationtroubleshootconnection"
MENU_BB_CANCELLATION_CONTINUE_TO_CANCEL             = "[menu].cancellationcontinuetocancel"
MENU_BB_CANCELLATION_TRANSFERRING_LOCATION          = "[menu].cancellationtransferinstallationlocation"
MENU_BB_CONFIRM_CANCELLATION                        = "[menu].confirmationcancel"
MENU_BB_DOWNGRADE_OFFER_1                           = "[menu].downgradeoffer1"
MENU_BB_DOWNGRADE_OFFER_2                           = "[menu].downgradeoffer2"
MENU_BB_DOWNGRADE_OFFER_3                           = "[menu].downgradeoffer3"
MENU_BB_DOWNGRADE_OTHER_PLAN                        = "[menu].downgradeotherplan"

#Customer Verification
MENU_YES_VERIFY                                     = "[menu].yesverify"
MENU_NO_VERIFY                                      = "[menu].noverify"
MENU_WHY_VERIFY                                     = "[menu].whyverify"

#Network Concern
MENU_SLOW_OR_NO_INTERNET                            = "[menu].slowornointernet"
MENU_TEXT                                           = "[menu].text"
MENU_CALLS                                          = "[menu].calls"
MENU_VOLTE                                          = "[menu].volte"
MENU_TODAY                                          = "[menu].todayMenu"
MENU_YESTERDAY                                      = "[menu].yesterdayMenu"
MENU_OTHER_DAY                                      = "[menu].otherDayMenu"
MENU_SLOW_INTERNET                                  = "[menu].slowinternet"
MENU_NO_INTERNET                                    = "[menu].nointernet"
MENU_LANDLINE                                       = "[menu].nolandline"

# SIM Registration
MENU_FAILED_SCAN                                    = "[menu].failedidscan"
MENU_FAILED_SELFIE                                  = "[menu].failedselfie"
MENU_PROBLEM_WITH_CAPTURE                           = "[menu].problemwithcapture"

# ****************** Thea Globe of Platinum *****************************************************************
MENU_GET_GLOBE_AT_HOME                            = "[menu].getglobeathome"

# ***********************************************************************************************************
# ************************************* MENUS WITH NO FLOW **************************************************
# *********************** put underscore before menu name to be identified as option menu *******************
# ***********************************************************************************************************
MENU_DISCON_REASONS_LOST_PHONE_OR_SIM               = "[menu]._lostphoneorsim"
MENU_DISCON_REASONS_OUT_OF_COUNTRY                  = "[menu]._outofcountry"
MENU_RECON_TD_LOST_PHONE_OR_SIM                     = "[menu]._reconlostphoneorsim"
MENU_RECON_TD_OUT_OF_COUNTRY                        = "[menu]._reconoutofcountry"


MENU_APPLIED_PRODUCT_POSTPAID_MOBILE                = "[menu]._appliedproductpostpaidmobile"
MENU_APPLIED_PRODUCT_POSTPAID_BROADBAND             = "[menu]._appliedproductpostpaidbroadband"
MENU_APPLIED_PRODUCT_GFIBER_PREPAID                 = "[menu]._appliedproductgfiberprepaid"
MENU_NEW_ADDITIONAL_LINE                            = "[menu]._newadditionalline"
MENU_RENEWAL                                        = "[menu]._renewal"
MENU_POSTPAID_NEW_LINE_ONLINE_WEBSITE               = "[menu]._postpaidnewlineonlinewebsite"
MENU_POSTPAID_NEW_LINE_GLOBE_STORE                  = "[menu]._postpaidnewlineglobestore"
MENU_POSTPAID_NEW_LINE_GLOBE_TELESALES              = "[menu]._postpaidnewlineglobetelesales"
MENU_POSTPAID_RENEWAL_ONLINE_WEBSITE                = "[menu]._postpaidrenewalonlinewebsite"
MENU_POSTPAID_RENEWAL_GLOBE_STORE                   = "[menu]._postpaidrenewalglobestore"
MENU_AREA_NCR                                       = "[menu]._areancr"
MENU_AREA_LUZON                                     = "[menu]._arealuzon"
MENU_AREA_VISMIN                                    = "[menu]._areavismin"
MENU_GLOBE_ONLINE_WEBSITE                           = "[menu]._onlinewebsite"
MENU_GLOBE_STORE                                    = "[menu]._globestore"
MENU_DOOR_TO_DOOR                                   = "[menu]._doortodoor"
MENU_GLOBE_TELESALES                                = "[menu]._globetelesales"
MENU_VERIFY_PAYMENT_CHANNEL_GLOBE_ONE_APP			= "[menu]._paymentchannel_globeoneapp"
MENU_VERIFY_PAYMENT_CHANNEL_GCASH    				= "[menu]._paymentchannel_gcash"
MENU_VERIFY_PAYMENT_CHANNEL_GLOBE_WEBSITE 			= "[menu]._paymentchannel_globewebsite"
MENU_VERIFY_PAYMENT_CHANNEL_GLOBE_STORE				= "[menu]._paymentchannel_globestore"
MENU_VERIFY_PAYMENT_CHANNEL_QUICKPAY				= "[menu]._paymentchannel_quickpay"
MENU_VERIFY_PAYMENT_CHANNEL_ECPAY					= "[menu]._paymentchannel_ecpay"
MENU_VERIFY_PAYMENT_CHANNEL_SEVENELEVEN				= "[menu]._paymentchannel_seveneleven"
MENU_VERIFY_PAYMENT_CHANNEL_BAYAD_CENTER 			= "[menu]._paymentchannel_bayadcenter"
MENU_VERIFY_PAYMENT_CHANNEL_SM						= "[menu]._paymentchannel_sm"
MENU_VERIFY_PAYMENT_CHANNEL_AUTOPAY					= "[menu]._paymentchannel_autopay"
MENU_VERIFY_PAYMENT_CHANNEL_BANK					= "[menu]._paymentchannel_bank"
MENU_VERIFY_PAYMENT_CHANNEL_OTHERS					= "[menu]._paymentchannel_others"
