# states
MAIN_MENU_STATE = "MENU"
ADVISORY_SHORT_STATE_P0 = "ADVISORY-PRIORITY-0-SHORT"
ADVISORY_SHORT_STATE_P1 = "ADVISORY-PRIORITY-1-SHORT"
ADVISORY_SHORT_STATE_P2 = "ADVISORY-PRIORITY-2-SHORT"
ADVISORY_AGENT_STATE_P0 = "ADVISORY-PRIORITY-0-AGENT" 
ADVISORY_AGENT_STATE_P1 = "ADVISORY-PRIORITY-1-AGENT"
ADVISORY_AGENT_STATE_P2 ="ADVISORY-PRIORITY-2-AGENT"
ADVISORY_EXIT_THEA_STATE = "ADVISORY-EXIT"
DPN_STATE = "DPN"
REG_STATE = "REG"
OTP_STATE = "OTP"
INTENT_STATE = "INT"
BUY_LOAD_STATE = "BUY"
PAY_BILL_STATE = "PAY-BILL"
INTENT_OTP_STATE = "INTOTP"
TRANSFER_STATE = "AGT"
MYB_MANAGING_STATE = "MYBMAN"
MYB_REGISTERING_STATE = "RYB"
MYB_REGISTERING_MENU_STATE = "RYBM"
MYB_REGISTERING_MENU_SP_STATE = "RYBM-SP"
MYB_REGISTERING_MENU_SP_PROCEED_STATE = "RYBM-SP-PROCEED"
MYB_REGISTERING_MENU_PAT_STATE = "RYBM-PAT"
MYB_REGISTERING_MENU_PAT_PROCEED_STATE = "RYBM-PAT-PROCEED"
MYB_REGISTERING_MENU_CORP_STATE = "RYBM-CORP"
MYB_REGISTERING_MENU_CORP_PROCEED_STATE = "RYBM-CORP-PROCEED"
MYB_REGISTERING_MENU_ONE_STATE = "RYBM-ONE"
MYB_REGISTERING_MENU_ONE_PROCEED_STATE = "RYBM-ONE-PROCEED"
MYB_REGISTERING_MENU_COOP_STATE = "RYBM-COOP"
MYB_REGISTERING_MENU_COOP_PROCEED_STATE = "RYBM-COOP-PROCEED"
MYB_REGISTERING_FAQ_STATE = "RYB-FAQ"
MYB_FAQ_LGU_STATE = "FAQ-LGU"
MYB_FAQ_DTI_STATE = "FAQ-DTI"
MYB_FAQ_SEC_STATE = "FAQ-SEC"
MYB_FAQ_CDA_STATE = "FAQ-CDA"
MYB_FAQ_BIR_STATE = "FAQ-BIR"
MYB_FAQ_MORE_STATE = "FAQ-more"
MYB_FAQ_DOLE_STATE = "FAQ-DOLE"
MYB_FAQ_SSS_STATE = "FAQ-SSS"
MYB_FAQ_PAGIBIG_STATE = "FAQ-PAGIBIG"
MYB_FAQ_PHILHEALTH_STATE = "FAQ-PHILHEALTH"
MYB_FAQ_LGU_BP_STATE = "FAQ-LGU-BP"
MYB_FAQ_LGU_OP_STATE = "FAQ-LGU-OP"
MYB_FAQ_LGU_C_STATE = "FAQ-LGU-C"
MYB_FAQ_LGU_I_STATE = "FAQ-LGU-I"
MYB_FAQ_DTI_BN_STATE = "FAQ-DTI-BN"
MYB_FAQ_DTI_R_STATE = "FAQ-DTI-R"
MYB_FAQ_DTI_F_STATE = "FAQ-DTI-F"
MYB_FAQ_DTI_GI_STATE = "FAQ-DTI-GI"
MYB_FAQ_SEC_P_STATE = "FAQ-SEC-P"
MYB_FAQ_SEC_C_STATE = "FAQ-SEC-C"
MYB_FAQ_SEC_R_STATE = "FAQ-SEC-R"
MYB_FAQ_CDA_GI_STATE = "FAQ-CDA-GI"
MYB_FAQ_CDA_M_STATE = "FAQ-CDA-M"
MYB_FAQ_CDA_R_STATE = "FAQ-CDA-R"
MYB_FAQ_BIR_GI_STATE = "FAQ-BIR-GI"
MYB_FAQ_BIR_T_STATE = "FAQ-BIR-T"
MYB_FAQ_BIR_R_STATE = "FAQ-BIR-R"
MYB_FAQ_DOLE_GI_STATE = "FAQ-DOLE-GI"
MYB_FAQ_DOLE_E_STATE = "FAQ-DOLE-E"
MYB_FAQ_DOLE_S_STATE = "FAQ-DOLE-S"
MYB_FAQ_DOLE_B_STATE = "FAQ-DOLE-B"
MYB_FAQ_SSS_GI_STATE = "FAQ-SSS-GI"
MYB_FAQ_SSS_C_STATE = "FAQ-SSS-C"
MYB_FAQ_SSS_SO_STATE = "FAQ-SSS-SO"
MYB_FAQ_PAGIBIG_GI_STATE = "FAQ-PAGIBIG-GI"
MYB_FAQ_PAGIBIG_C_STATE = "FAQ-PAGIBIG-C"
MYB_FAQ_PHILHEALTH_GI_STATE = "FAQ-PHILHEALTH-GI"
MYB_FAQ_PHILHEALTH_C_STATE = "FAQ-PHILHEALTH-C"
MYB_FAQ_PHILHEALTH_E_STATE = "FAQ-PHILHEALTH-E"
BTS_STATE = "BTS"
BTS_CMC_STATE = "BTS-CMC"
BTS_CMC_IC_STATE = "BTS-CMC-IC"
BTS_CMC_TN_STATE = "BTS-CMC-TN"
BTS_CRC_STATE = "BTS-CRC"
BTS_CRC_NS_STATE = "BTS-CRC-NS"
BTS_CST_STATE = "BTS-CST"
BTS_CST_NS_STATE = "BTS-CST-NS"
BTS_CST_ILT_STATE = "BTS-CST-ILT"
BTS_CRT_STATE = "BTS-CRT"
BTS_CRT_NS_STATE = "BTS-CRT-NS"
BTS_NO_SIGNAL_STATE = "BTS-NS"
BTS_INTERNET_CONNECTION_STATE = "BTS-IC"
BTS_PROMO_REG_STATE = "BTS-PR"
BTS_YES_MENU_STATE = "BTS-YES-MENU"
BTS_YES_STATE = "BTS-YES"
BTS_YES_NO_SIGNAL_STATE = "BTS-YES-NS"
BTS_YES_NO_CALL_STATE = "BTS-YES-NC"
BTS_YES_DROPPED_CALL_STATE = "BTS-YES-DC"
BTS_YES_NO_TEXT_STATE = "BTS-YES-NT"
BTS_YES_NO_DATA_STATE = "BTS-YES-ND"
LANG_STATE = "LANG"
REPORT_STATE = "RPT"
SHOP_VOUCHER_STATE = "SHOP-VOUCHER"
RENEW_PLAN_STATE = "RNP"
RENEW_ONE_ACCOUNT_STATE = "RPOA"
RENEW_PLAN_ADVISORY_STATE = "RNP-ADV"
REPORT_SPAM_STATE = "RPT-SPAM"
BIRTHDAY_TREATS_STATE = "BDAY-TREATS"
TERMINATE_LINE_STATE = "TERMINATE-LINE"
RECONNECT_LINE_STATE = 'RECONNECT-LINE'
GO_HEALTH_STATE ='GO-HEALTH'
OTHER_GLOBE_ACCOUNT_STATE = "OTHER-GLOBE-ACCOUNT"


MYB_REGISTERING_LIST = [MYB_REGISTERING_STATE, MYB_REGISTERING_MENU_STATE, MYB_REGISTERING_MENU_SP_STATE,
                        MYB_REGISTERING_MENU_SP_PROCEED_STATE, MYB_REGISTERING_MENU_PAT_STATE,
                        MYB_REGISTERING_MENU_PAT_PROCEED_STATE, MYB_REGISTERING_MENU_CORP_STATE,
                        MYB_REGISTERING_MENU_CORP_PROCEED_STATE, MYB_REGISTERING_MENU_ONE_STATE,
                        MYB_REGISTERING_MENU_ONE_PROCEED_STATE, MYB_REGISTERING_MENU_COOP_STATE,
                        MYB_REGISTERING_MENU_COOP_PROCEED_STATE, MYB_REGISTERING_FAQ_STATE, MYB_FAQ_LGU_STATE,
                        MYB_FAQ_DTI_STATE, MYB_FAQ_DOLE_STATE, MYB_FAQ_SSS_STATE, MYB_FAQ_PAGIBIG_STATE, MYB_FAQ_PHILHEALTH_STATE,
                        MYB_FAQ_SEC_STATE, MYB_FAQ_CDA_STATE, MYB_FAQ_BIR_STATE,
                        MYB_FAQ_MORE_STATE, MYB_FAQ_LGU_BP_STATE, MYB_FAQ_LGU_OP_STATE, MYB_FAQ_LGU_C_STATE,
                        MYB_FAQ_LGU_I_STATE, MYB_FAQ_DTI_BN_STATE, MYB_FAQ_DTI_R_STATE, MYB_FAQ_DTI_F_STATE,
                        MYB_FAQ_DTI_GI_STATE, MYB_FAQ_SEC_P_STATE, MYB_FAQ_SEC_C_STATE, MYB_FAQ_SEC_R_STATE,
                        MYB_FAQ_CDA_GI_STATE, MYB_FAQ_CDA_M_STATE, MYB_FAQ_CDA_R_STATE, MYB_FAQ_BIR_GI_STATE,
                        MYB_FAQ_BIR_T_STATE, MYB_FAQ_BIR_R_STATE, MYB_FAQ_DOLE_GI_STATE, MYB_FAQ_DOLE_E_STATE,
                        MYB_FAQ_DOLE_S_STATE, MYB_FAQ_DOLE_B_STATE, MYB_FAQ_SSS_GI_STATE, MYB_FAQ_SSS_C_STATE,
                        MYB_FAQ_SSS_SO_STATE, MYB_FAQ_PAGIBIG_GI_STATE, MYB_FAQ_PAGIBIG_C_STATE, MYB_FAQ_PHILHEALTH_GI_STATE, MYB_FAQ_PHILHEALTH_C_STATE, MYB_FAQ_PHILHEALTH_E_STATE]

MYB_REG_FAQS = [MYB_FAQ_LGU_STATE, MYB_FAQ_DTI_STATE, MYB_FAQ_DOLE_STATE, MYB_FAQ_SSS_STATE, MYB_FAQ_PAGIBIG_STATE, 
                MYB_FAQ_PHILHEALTH_STATE, MYB_FAQ_SEC_STATE, MYB_FAQ_CDA_STATE, MYB_FAQ_BIR_STATE]

BTS_LIST = [BTS_STATE, BTS_CMC_STATE, BTS_CMC_IC_STATE, BTS_CMC_TN_STATE, BTS_CRC_STATE, BTS_CRC_NS_STATE, 
            BTS_CST_STATE, BTS_CST_NS_STATE, BTS_CST_ILT_STATE, BTS_CRT_STATE, BTS_CRT_NS_STATE, BTS_NO_SIGNAL_STATE, 
            BTS_INTERNET_CONNECTION_STATE, BTS_PROMO_REG_STATE, BTS_YES_MENU_STATE, BTS_YES_STATE, 
            BTS_YES_NO_SIGNAL_STATE, BTS_YES_NO_CALL_STATE, BTS_YES_DROPPED_CALL_STATE, BTS_YES_NO_TEXT_STATE, 
            BTS_YES_NO_DATA_STATE]


REFLINK_DPN_STATE = "REFLINK-DPN"
REFLINK_TRANSFER_STATE = "REFLINK-TRANSFER"
REFLINK_STATE = "REFLINK"

INSTALLMENT_PAYMENT_STATE = "INSTPAYMENT"
REGFFUP_STATE = "REGFFUP"
CHICAGO_STATE = "CHCG"
AMAX_FAQS_STATE ="AMAX-FAQS"

VOUCHER_STATE = "VCH"
UPGRADE_PLATINUM_STATE = "UPGD-PLAT"

CAMPAIGN_1_STATE = "CAMPAIGN-1"
CAMPAIGN_2_STATE = "CAMPAIGN-2"
CAMPAIGN_3_STATE = "CAMPAIGN-3"
CAMPAIGN_4_STATE = "CAMPAIGN-4"

# GAH States
GAH_TRANSFER_STATE = 'GAH-TRANSFER'

# Chicago V2
CHICAGO_V2_STATE = "XMAS"
# NIA States
REPORT_A_PROBLEM_STATE = "REPORT-PROBLEM-SUB"
OTHER_REQUESTS_STATE = "OTHER-REQ-SUB"
ACCOUNT_INFORAMTION_STATE = "ACCOUNT-INFO-SUB"
ACCOUNT_NUMBER_STATE = "ACCOUNT-NUM"
GET_REWARDS_STATE = "GET-REWARDS"
CHANGE_PLAN_STATE = "CHANGE-PLAN"
TERMINATE_LINE_STATE= "TERMINATE-LINE"

# Redeem Rewards
REDEEM_REWARDS_STATE = "RDM-RWRDS"

# Know Contract End Date
CONTRACT_END_DATE_STATE = "CONTRACT-END"
# Check Application Status
CHECK_APPLICATION_STATUS_STATE = "CHECK-APP-STAT"

APPLY_NEW_LINE_STATE = "APPLY-NEW-LINE"

# NIAS 2.0
SPAM_OR_SCAM_STATE = "SPAM-SCAM"
FRAUD_REPORT_ILLEGAL_REPEATERS_STATE = "REPORT-ILLEGAL-REPEATERS"
FRAUD_REPORT_FRAUD_STATE = "REPORT-FRAUD-STATE"

LOSTPHONE_OR_SIM_STATE = "LOSTPHONE-OR-SIM"
HOW_TOS_STATE = "HOW-TO"
ACTIVATE_FREEBIES_STATE = "ACTIVATE-FREEBIES"
ACTIVATE_SIM_STATE ="ACTIVATE-SIM"
SESSION_END_CONFIRMATION_STATE = "SESSION-END-CONFIRMATION"
CHECK_APPLICATION_STATE                         = "CHECK-APPLICATION"
CHECK_APPLICATION_PRODUCT_STATE                 = "CHECK-APPLICATION-PRODUCT"
CHECK_APPLICATION_POSTPAID_STATE                = "CHECK-APPLICATION-POSTPAID"
CHECK_APPLICATION_BROADBAND_STATE               = "CHECK-APPLICATION-BROADBAND"
CHECK_APPLICATION_FOLLOW_UP_STATE               = "CHECK-APPLICATION-FOLLOW-UP"
CHECK_APPLICATION_RENEWAL_STATE                 = "CHECK-APPLICATION-RENEWAL"
CHECK_APPLICATION_POSTPAID_MOBILE_STATE         = "check-app-postpaid-mobile"
CHECK_APPLICATION_POSTPAID_BROADBAND_STATE      = "check-app-postpaid-broadband"
CHECK_APPLICATION_GFIBER_PREPAID_STATE          = "check-app-gfiber-prepaid"
CHECK_NEW_APPLICATION_PP_ONLINE_WEBSITE_STATE = "CHECK-NEW-APPLICATION-PP-ONLINE-WEBSITE"
CHECK_NEW_APPLICATION_PP_GLOBE_STORE_STATE = "CHECK-NEW-APPLICATION-PP-GLOBE-STORE"
CHECK_NEW_APPLICATION_PP_TELESALES_STATE = "CHECK-NEW-APPLICATION-PP-TELESALES"
CHECK_NEW_APPLICATION_BB_ONLINE_WEBSITE_STATE = "CHECK-NEW-APPLICATION-BB-ONLINE-WEBSITE"
CHECK_NEW_APPLICATION_BB_GLOBE_STORE_STATE = "CHECK-NEW-APPLICATION-BB-GLOBE-STORE"
CHECK_NEW_APPLICATION_BB_DOOR_TO_DOOR_STATE = "CHECK-NEW-APPLICATION-BB-DOOR-TO-DOOR"
CHECK_NEW_APPLICATION_BB_TELESALES_STATE = "CHECK-NEW-APPLICATION-BB-TELESALES"
CHECK_RENEW_APPLICATION_ONLINE_WEBSITE_STATE = "CHECK-RENEW-APPLICATION-ONLINE-WEBSITE"
CHECK_RENEW_APPLICATION_GLOBE_STORE_STATE = "CHECK-RENEW-APPLICATION-GLOBE-STORE"
FOLLOWUP_CONCERN_STATE = "FOLLOWUP-CONCERN"
FOLLOWUP_CONCERN_VIP_USER_STATE = "FOLLOWUP-CONCERN-VIP-USER"

TECHNICIAN_VISIT_STATE = "TECHNICIAN-VISIT"
RECONNECT_MY_LINE_STATE = "RECONNECT-MY-LINE"
RECONNECT_MY_LINE_XFER_TO_AGENT_STATE = "RECONNECT-MY-LINE-XFER-TO-AGENT"
RENEW_PLAN_STATE = "RENEW-PLAN"
RENEW_PLAN_IPHONE13_RESERVE_NOW_STATE = "RENEW-PLAN-IPHONE13-RESERVE-NOW"
RENEW_PLAN_IPHONE13_CHECK_STATUS_STATE = "RENEW-PLAN-IPHONE13-CHECK-STATUS"
RENEW_PLAN_CHECK_ELIGIBILITY_STATE = "RENEW-PLAN-CHECK-ELIGIBILITY"
RENEW_PLAN_VISIT_ONLINE_SHOP_STATE = "RENEW-PLAN-VISIT-ONLINE-SHOP"
RENEW_PLAN_REPORT_ONLINE_ISSUE_STATE = "RENEW-PLAN-REPORT-ONLINE-ISSUE"
RENEW_PLAN_FOLLOWUP_ORDER_STATE = "RENEW-PLAN-FOLLOWUP-ORDER"

APPLY_NEW_LINE_STATE = "APPLY-A-NEW-LINE"
BUY_LOAD_OR_PROMO_STATE = "BUY-LOAD-OR-PROMO"
LOAD_PROMOS_AND_REWARDS_STATE = "LOAD-PROMOS-AND-REWARDS"
MODIFY_OR_TERMINATE_STATE = 'MODIFY-OR-TERMINATE'
MODIFY_OR_TERMINATE_BB_STATE = 'MODIFY-OR-TERMINATE-BB'
MODIFY_OR_TERMINATE_BB_UPGRADE_PLAN_STATE = 'MOD-OR-TERM-BB-UPGRADE-PLAN'
MODIFY_OR_TERMINATE_BB_DOWNGRADE_PLAN_STATE = 'MOD-OR-TERM-BB-DOWNGRADE-PLAN'
MODIFY_OR_TERMINATE_BB_TEMP_DISCONN_STATE = 'MOD-OR-TERM-BB-TEMP-DISCONN'
MODIFY_OR_TERMINATE_BB_TERMINATION_STATE = 'MOD-OR-TERM-BB-TERMINATION'
MODIFY_OR_TERMINATE_BB_TRANSFER_LOCATION_STATE = 'MOD-OR-TERM-BB-XFER-LOC'
MODIFY_OR_TERMINATE_BB_TRANSFER_OWNERSHIP_STATE = 'MOD-OR-TERM-BB-XFER-OWNERSHIP'
MODIFY_OR_TERMINATE_BB_OTHER_REQUESTS_STATE = 'MOD-OR-TERM-BB-OTHER-REQ'
MODIFY_OR_TERMINATE_BB_FOLLOWUP_STATE = 'MOD-OR-TERM-BB-FOLLOWUP'
MODIFY_OR_TERMINATE_BB_UPSELL_GET_OFFER_1_STATE = 'MOD-OR-TERM-BB-UPSELL-GET-OFFER-1'
MODIFY_OR_TERMINATE_BB_UPSELL_GET_OFFER_2_STATE = 'MOD-OR-TERM-BB-UPSELL-GET-OFFER-2'
MODIFY_OR_TERMINATE_BB_UPSELL_GET_OFFER_3_STATE = 'MOD-OR-TERM-BB-UPSELL-GET-OFFER-3'
MODIFY_OR_TERMINATE_BB_UPSELL_GET_OFFER_GENERIC_STATE = 'MOD-OR-TERM-BB-UPSELL-GET-OFFER-GENERIC'
MODIFY_OR_TERMINATE_VIP_USER_STATE = "MODIFY-OR-TERMINATE-VIP-USER"
MODIFY_OR_TERMINATE_BB_UPSELL_NWL_UPGRADE_NOW_STATE = "MOD-OR-TER-BB-UPSELL-NWL-UPGRADE-NOW"
MODIFY_OR_TERMINATE_BB_UPSELL_NWL_MORE_QUESTION_STATE = "MOD-OR-TER-BB-UPSELL-NWL-MORE-QUESTION"
MODIFY_OR_TERMINATE_BB_UPSELL_NWL_NOT_PROCEED_STATE = "MOD-OR-TER-BB-UPSELL-NWL-NOT-PROCEED"
MODIFY_OR_TERMINATE_BB_UPSELL_NWL_NON_GPON_STATE = "MOD-OR-TER-BB-UPSELL-NWL-NON-GPON"
MODIFY_OR_TERMINATE_BB_XFER_TO_AGENT_STATE = 'MOD-OR-TERM-BB-XFER-TO-AGENT'
MODIFY_OR_TERMINATE_CAIF_WHITELISTED_FOLLOWUP_STATE = "MOD-OR-TER-CAIF-WL-FOLLOWUP"
MODIFY_OR_TERMINATE_PREPAID_SIM_REQUEST_STATE = "MOD-OR-TER-PREPAID-SIM-REQUEST"
MODIFY_OR_TERMINATE_POSTPAID_SIM_REQUEST_STATE = "MOD-OR-TER-POSTPAID-SIM-REQUEST"
MODIFY_OR_TERMINATE_POSTPAID_TERMINATE_INSTALLMENT_PAYMENT_STATE ="MOD-OR-TER-POSTPAID-TERMINATE-INSTALLMENT-PAYMENT"
MODIFY_OR_TERMINATE_POSTPAID_TERMINATE_CHANGE_PLAN_STATE ="MOD-OR-TER-POSTPAID-TERMINATE-CHANGE-PLAN"
MODIFY_OR_TERMINATE_POSTPAID_TERMINATE_CHANGE_PLAN_WITH_DEVICE_STATE = "MOD-OR-TER-POSTPAID-TERMINATE-CHANGE-PLAN-WITH-DEVICE"
MODIFY_OR_TERMINATE_POSTPAID_TERMINATE_PORT_NUMBER_STATE ="MOD-OR-TER-POSTPAID-TERMINATE-PORT-NUMBER"
MODIFY_OR_TERMINATE_POSTPAID_TERMINATE_CANCEL_PLAN_STATE ="MOD-OR-TER-POSTPAID-TERMINATE-CANCEL-PLAN"
MODIFY_OR_TERMINATE_BB_CANCEL_REASON_STATE = "MOD-OR-TER-BB-CANCEL-REASON"
MODIFY_OR_TERMINATE_BB_CANCEL_FINANCIAL_CONCERNS_STATE = "MOD-OR-TER-BB-CANCEL-FINANCIAL-CONCERNS"
MODIFY_OR_TERMINATE_BB_CANCEL_SWITCHING_COMPETITOR_STATE = "MOD-OR-TER-BB-CANCEL-SWITCHING-COMPETITOR"
MODIFY_OR_TERMINATE_BB_CANCEL_CONNECTION_ISSUES_STATE = "MOD-OR-TER-BB-CANCEL-CONNECTION-ISSUES"
MODIFY_OR_TERMINATE_BB_CANCEL_TRANSFERRING_LOCATION_STATE = "MOD-OR-TER-BB-CANCEL-TRANSFERRING-LOCATION"
MODIFY_OR_TERMINATE_BB_CANCEL_OTHERS_STATE = "MOD-OR-TER-BB-CANCEL-OTHERS"
MODIFY_OR_TERMINATE_BB_CONTINUE_TO_CANCEL_STATE = "MOD-OR-TER-BB-CONTINUE-TO-CANCEL"
MODIFY_OR_TERMINATE_BB_EXPLORE_PLANS_STATE = "MOD-OR-TER-BB-EXPLORE-PLANS"
MODIFY_OR_TERMINATE_BB_CANCELLATION_STATE = "MOD-OR-TER-BB-CANCELLATION"
MODIFY_OR_TERMINATE_XFER_TO_AGENT_STATE = 'MOD-OR-TERM-XFER-TO-AGENT'
MODIFY_OR_TERMINATE_BB_RETENTION_STATE = 'MOD-OR-TERM-RETENTION'

FORM_TO_MAIL_STATE = 'FORM-TO-MAIL'
EMPLOYEE_CARE_STATE = 'EMPLOYEE-CARE'
SESSION_END_CONFIRMATION_EE_STATE = 'SESSION-END-CONFIRMATION-EE'

MODIFY_OR_TERMINATE_CHANGE_PLAN_STATE = 'MODIFY-OR-TERMINATE-CHANGE-PLAN'
MODIFY_OR_TERMINATE_TERMINATE_LINE_STATE = 'MODIFY-OR-TERMINATE-TERMINATE-LINE'

# Account Requests
ACCOUNT_REQUESTS_STATE = "ACCOUNT-REQUESTS"
TRANSFER_OWNERSHIP_STATE = 'XFER-OWNR'
REPLACE_RETURN_DEVICE_STATE = 'RPL-RTRN-DVC'
UNLOCK_DEVICE_STATE = 'UNLK-DVC'
PORT_NUMBER_STATE = 'PORT-NUM'
ACCOUNT_OTHERS_STATE = 'ACCT-OTHERS'
ACCOUNT_FOLLOWUP_STATE = 'ACCT-FOLLOWUP'
PORT_NUM_DID_NOT_RECEIVE_OTP_STATE = 'PORTNUM-DIDNT-RCV-OTP'
PORT_NUM_ENCOUNTERED_ERROR_STATE = 'PORTNUM-ENCTRD-ERR'
PORT_NUM_G1_DISPLAYS_ONL_BRAND_STATE = 'PORTNUM-G1-OLD-BRAND'

# Check Balance
CHECK_BALANCE_STATE = "CHECK-BALANCE"

# Network Concern 
NETWORK_CONCERN_STATE = 'NETWORK-CONCERN'
NETWORK_CONCERN_MOBILE_STATE = 'NETWORK-CONCERN-MOBILE'
NETWORK_CONCERN_CEM_MOBILE_STATE = 'NETWORK-CONCERN-CEM-MOBILE'
NETWORK_CONCERN_BROADBAND_STATE = 'NETWORK-CONCERN-BROADBAND'
NETWORK_CONCERN_HPW_STATE = 'NETWORK-CONCERN-HPW'
NETWORK_CONCERN_VIP_USER_STATE = "NETWORK-CONCERN-VIP-USER"

#Bills and payment
BILLS_AND_PAYMENTS_STATE = "BILLS-AND-PAYMENTS"
BILLS_AND_PAYMENTS_VIP_USER_STATE = "BILLS-AND-PAYMENTS-VIP-USER"
UNREFLECTED_BILL_STATE = "RECENT-PAYMENT-NOT-YET-REFLECTED"
UNKNOWN_CHARGES_STATE = "UNKNONW-CHARGES-IN-BILL"
HOW_TO_READ_MY_BILL_STATE = "HOW-TO-READ-MY-BILL"
B_A_P_NEW_CUSTOMER_STATE = "B-A-P-NEW-CUSTOMER"
B_A_P_REMAINING_BALANCE_STATE = "B-A-P-REMAINING-BALANCE"
B_A_P_UPGRADED_TO_FIBER_STATE = "B-A-P-UPGRADED-TO-FIBER"
B_A_P_SPEED_UPGRADED_STATE = "B-A-P-SPEED-UPGRADED"
B_A_P_AVAILED_DEVICES_STATE = "B-A-P-AVAILED-DEVICES"
UNRECEIVED_BILL_STATE = "DIDNT-RECEIVED-BILL"
B_A_P_OTHERS_STATE = "BILL_N_PAYMENT_OTHERS"
B_A_P_FFUP_STATE = "BILL_N_PAYMENT_FF_UP"
B_A_P_INSTALLMENT_STATE = "BILL_N_PAYMENT_INSTALLMENT"
B_A_P_FINANCIAL_CARE_STATE = "BILL_N_PAYMENT_FINANCIAL_CARE"

#REFLINK
REFLINK_CHANGE_PLAN_STATE = "REFLINK-CHANGE-PLAN"
REFLINK_RENEW_PLAN_STATE = "REFLINK-RENEW-PLAN"
REFLINK_CONCIERGE_STATE = "REFLINK-CONCIERGE"
REFLINK_PLATINUM_UPGRADE_STATE = "REFLINK-PLATINUM-UPGRADE"

#SIM Registration
REGISTER_SIM_STATE = "REGISTER-SIM"
FAQ_SIM_STATE = "FAQ-SIM"
ISSUE_WITH_SIM_STATE = "ISSUE-WITH-SIM"

WHY_REGISTER_SIM_STATE = "WHY-REGISTER-SIM"
WHO_TO_REGISTER_SIM_STATE = "WHO-TO-REGISTER-SIM"
HOW_TO_REGISTER_SIM_STATE = "HOW-TO-REGISTER-SIM"
WHAT_NEED_REGISTER_SIM_STATE = "WHAT-NEEDS-TO-REGISTER-SIM"
CHANGE_REG_INFO_SIM_STATE = "CHANGE-REG-INFO-SIM"
OTHER_CONCERNS_SIM_STATE = "OTHER-CONCERNS-SIM"

ISSUES_IN_REG_SIM_STATE = "ISSUES-IN-REG-SIM"
DIDNT_RECEIVE_OTP_SIM_STATE = "DIDNT-RECEIVE-OTP-SIM"
CANT_EDIT_UPLOAD_SIM_STATE = "CANT-EDIT-UPLOAD-SIM"

DIDNT_RECEIVE_CONFIRMATION_SIM_STATE = "DIDNT-RECEIVE-CONFIRMATION-SIM"
DIDNT_SAVE_REF_NUM_SIM_STATE = "DIDNT-SAVE-REF-NUM-SIM"
CANT_USE_SERVICE_SIM_STATE = "CANT-USE-SERVICE-SIM"
FAILED_SCAN_STATE                   = "failed-scan"
FAILED_SELFIE_STATE                 = "failed-selfie"
PROBLEM_WITH_CAPTURE_STATE          = "problem-with-capture"

#Globe One Concerns
GLOBE_ONE_CONCERNS_STATE = "GLOBE-ONE-CONCERNS"
GLOBE_ONE_APP_EXP_STATE = "GLOBE-ONE-APP-EXP-STATE"
GLOBE_ONE_PAYMENT_ISSUE_STATE = "GLOBE-ONE-PAYMENT-ISSUE-STATE"
GLOBE_ONE_LOAD_PROMO_ISSUE_STATE = "GLOBE-ONE-LOAD-PROMO-ISSUE-STATE"
GLOBE_ONE_LOGIN_REG_ISSUE_STATE = "GLOBE-ONE-LOGIN-REG-ISSUE-STATE"
GLOBE_ONE_SAVE_TO_DB_STATE = "GLOBE-ONE-SAVE-TO-DB-STATE"
GLOBE_ONE_ERROR_GOTTEN_STATE = "GLOBE-ONE-ERROR-GOTTEN-STATE"
GLOBE_ONE_CANT_REGISTER_PROMO_STATE = "GLOBE-ONE-CANT-REGISTER-PROMO-STATE"
GLOBE_ONE_REG_LOGIN_ISSUE_STATE = "GLOBE-ONE-REG-LOGIN-ISSUE-STATE"
GLOBE_ONE_ISSUE_SELECTED_STATE = "GLOBE-ONE-ISSUE-SELECTED-STATE"
GLOBE_ONE_CANT_ADD_ACCOUNT_OPTIONS_STATE = "GLOBE-ONE-CANT-ADD-ACCOUNT-OPTIONS-STATE"

#Customer Verification
CUSTOMER_VERIFICATION_STATE = "CUSTOMER-VERIFICATION-STATE"
CUSTOMER_VERIFICATION_YES_STATE = "CUSTOMER-VERIFICATION-YES-TO-VERIFY-STATE"
CUSTOMER_VERIFICATION_NO_STATE = "CUSTOMER-VERIFICATION-NO-TO-VERIFY-STATE"
CUSTOMER_VERIFICATION_WHY_STATE = "CUSTOMER-VERIFICATION-WHY-TO-VERIFY-STATE"
#THEA
THEA_REGISTRATION_STATE ="THEA-REGISTRATION"
THEA_MAIN_MENU_STATE ="THEA-MAIN-MENU"
THEA_NIA_MENU_STATE ="THEA-NIA-MENU"
THEA_INPUT_ANOTHER_ACCOUNT_STATE = "THEA-NIA-MENU"
THEA_CONCIERGE_STATE = "CONCIERGE"
THEA_GCASH_PLATINUM_STATE = "GCASH-PLATINUM"
PLATINUM_UPGRADE_STATE = "PLATINUM-UPGRADE"
EXIT_PLATINUM_UPGRADE_STATE = "EXIT-PLATINUM-UPGRADE"

#THEA NIA MENU SESSION STATES
THEA_NETWORK_CONCERN_STATE = 'THEA-NETWORK-CONCERN'
THEA_LOAD_PROMOS_REWARDS_STATE = 'THEA-LOAD_PROMOS_REWARDS'
THEA_BILLS_AND_PAYMENTS_STATE = 'THEA-BILLS-AND-PAYMENTS'
THEA_RECONNECT_MY_LINE_STATE = 'THEA-RECONNECT-MY-LINE'
THEA_MODIFY_OR_TERMINATE_STATE = 'THEA-MODIFY-OR-TERMINATE'
THEA_ACCOUNT_REQUESTS_STATE = 'THEA-ACCOUNT-REQUESTS'
THEA_APPLICATION_ORDER_STATE = 'THEA-APPLICATION-ORDER'
THEA_FOLLOW_UP_CONCERN_STATE = 'THEA-FOLLOW-UP-CONCERN'
THEA_TECHNICIAN_VISIT_STATE = 'THEA-TECHNICIAN-VISIT'
THEA_RENEW_MY_PLAN_STATE = 'THEA-RENEW-MY-PLAN'
THEA_GET_GLOBE_HOME_STATE = 'THEA-GET-GLOBE-HOME'
THEA_BUY_LOAD_OR_PROMOS_STATE = 'THEA-BUY-LOAD-OR-PROMOS'
THEA_ACTIVATE_SIM_STATE = 'THEA-ACTIVATE-SIM'
THEA_ACTIVATE_FREEBIES_STATE = 'THEA-ACTIVATE-FREEBIES'
THEA_HOW_TOS_STATE = 'THEA-HOW-TOS'
THEA_SPAM_OR_SCAM_STATE = 'THEA-SPAM-OR-SCAM'
THEA_LOSTPHONE_OR_SIM_STATE = 'THEA-LOSTPHONE-OR-SIM'
THEA_CAMPAIGN_1_STATE = 'THEA-CAMPAIGN-1'
THEA_BIRTHDAY_TREATS_STATE = 'THEA-BIRTHDAY-TREATS'

GCASH_CONCERNS_STATE = "GCASH-CONCERNS"

# Chat to call
CHAT_TO_CALL_STATE = 'CHAT-TO-CALL'

#PREPAID FIBER
PREPAID_FIBER_OTHERS_STATE = 'PREPAID-FIBER-OTHERS'
PREPAID_FIBER_NETWORK_STATE = 'PREPAID-FIBER-NETWORK'
PREPAID_FIBER_MODIFY_AND_TERMINATE_STATE = 'PREPAID-FIBER-MODIFY-AND-TERMINATE'
PREPAID_FIBER_RECONNECT_STATE = 'PREPAID-FIBER-RECONNECT'
PREPAID_FIBER_LPR_STATE = 'PREPAID-FIBER-LPR'
PREPAID_FIBER_BILL_STATE = 'PREPAID-FIBER-BILL'
PREPAID_FIBER_FOLLOW_UP_STATE = 'PREPAID-FIBER-FOLLOW-UP'

PREPAID_FIBER_OPTION_STATE = 'PREPAID-FIBER-OPTION'
PREPAID_FIBER_MENU_MAPPING = {
    PREPAID_FIBER_OTHERS_STATE: ['othersprepaidfiber', 'othersotheraccount'],
    PREPAID_FIBER_NETWORK_STATE: ['networkprepaidfiber', 'networkotheraccount'],
    PREPAID_FIBER_MODIFY_AND_TERMINATE_STATE: ['modifyandterminateprepaidfiber','modifyandterminateotheraccount'],
    PREPAID_FIBER_RECONNECT_STATE: ['reconnectprepaidfiber','reconnectotheraccount'],
    PREPAID_FIBER_LPR_STATE: ['lprprepaidfiber', 'lprotheraccount'],
    PREPAID_FIBER_BILL_STATE: ['billprepaidfiber', 'billotheraccount'],
    PREPAID_FIBER_FOLLOW_UP_STATE: ['followupprepaidfiber', 'followupotheraccount']
}

#PLATINUM PROACTIVE RENEWAL
PROACTIVE_RENEWAL_STATE = 'PROACTIVE-RENEWAL'

GET_GLOBE_AT_HOME_STATE                         = "GET-GLOBE-AT-HOME"
ROAMING_STATE                                   = "ROAMING"


