OFFER_GROUP_1 = {
	"offer-1": "Krispy Kreme",
	"offer-2": "Max's",
	"offer-3": "ShopeePay Credits"
}

OFFER_GROUP_2 = {
	"offer-1": "Yellow Cab",
	"offer-2": "National Bookstore",
	"offer-3": "foodpanda"
}

OFFER_GROUP_3 = {
	"offer-1": "Pancake House",
	"offer-2": "Red Ribbon Butter Mamon",
	"offer-3": "Mercury Drug"
}

OFFER_GROUP_4 = {
	"offer-1": "Zalora",
	"offer-2": "Jollibee Mini Vanilla Sundae",
	"offer-3": "1pc Chickenjoy"
}

OFFER_DATE = {
    "2022": {
        "05": {
            "01": OFFER_GROUP_3,
            "02": OFFER_GROUP_3,
            "03": OFFER_GROUP_3,
            "04": OFFER_GROUP_3,
            "05": OFFER_GROUP_3,
            "06": OFFER_GROUP_3,
            "07": OFFER_GROUP_3,
            "08": OFFER_GROUP_3,
            "09": OFFER_GROUP_3,
            "10": OFFER_GROUP_3,
            "11": OFFER_GROUP_4,
            "12": OFFER_GROUP_4,
            "13": OFFER_GROUP_4,
            "14": OFFER_GROUP_4,
            "15": OFFER_GROUP_4,
            "16": OFFER_GROUP_4,
            "17": OFFER_GROUP_4,
            "18": OFFER_GROUP_4,
            "19": OFFER_GROUP_4,
            "20": OFFER_GROUP_4,
            "21": OFFER_GROUP_4,
            "22": OFFER_GROUP_4,
            "23": OFFER_GROUP_4,
            "24": OFFER_GROUP_4,
            "25": None,
            "26": None,
            "27": None,
            "28": None,
            "29": None,
            "30": None,
            "31": OFFER_GROUP_3
        },
        "06": {
            "01": OFFER_GROUP_1,
            "02": OFFER_GROUP_1,
            "03": OFFER_GROUP_1,
            "04": OFFER_GROUP_1,
            "05": OFFER_GROUP_1,
            "06": OFFER_GROUP_1,
            "07": OFFER_GROUP_1,
            "08": OFFER_GROUP_1,
            "09": OFFER_GROUP_1,
            "10": OFFER_GROUP_1,
            "11": OFFER_GROUP_1,
            "12": OFFER_GROUP_1,
            "13": OFFER_GROUP_2,
            "14": OFFER_GROUP_2,
            "15": OFFER_GROUP_2,
            "16": OFFER_GROUP_2,
            "17": OFFER_GROUP_2,
            "18": OFFER_GROUP_2,
            "19": OFFER_GROUP_2,
            "20": OFFER_GROUP_2,
            "21": OFFER_GROUP_2,
            "22": OFFER_GROUP_2,
            "23": OFFER_GROUP_2,
            "24": OFFER_GROUP_2,
            "25": OFFER_GROUP_2,
            "26": OFFER_GROUP_2,
            "27": OFFER_GROUP_3,
            "28": OFFER_GROUP_3,
            "29": OFFER_GROUP_3,
            "30": OFFER_GROUP_3
        },
        "07": {
            "01": OFFER_GROUP_3,
            "02": OFFER_GROUP_3,
            "03": OFFER_GROUP_3,
            "04": OFFER_GROUP_3,
            "05": OFFER_GROUP_3,
            "06": OFFER_GROUP_3,
            "07": OFFER_GROUP_3,
            "08": OFFER_GROUP_3,
            "09": OFFER_GROUP_3,
            "10": OFFER_GROUP_3,
            "11": OFFER_GROUP_4,
            "12": OFFER_GROUP_4,
            "13": OFFER_GROUP_4,
            "14": OFFER_GROUP_4,
            "15": OFFER_GROUP_4,
            "16": OFFER_GROUP_4,
            "17": OFFER_GROUP_4,
            "18": OFFER_GROUP_4,
            "19": OFFER_GROUP_4,
            "20": OFFER_GROUP_4,
            "21": OFFER_GROUP_4,
            "22": OFFER_GROUP_4,
            "23": OFFER_GROUP_4,
            "24": OFFER_GROUP_4,
            "25": None,
            "26": None,
            "27": None,
            "28": None,
            "29": None,
            "30": "ABRA_EARTHQUAKE",
            "31": "ABRA_EARTHQUAKE"
        },
        "08": {
            "01": "ABRA_EARTHQUAKE",
            "02": "ABRA_EARTHQUAKE",
            "03": "ABRA_EARTHQUAKE",
            "04": "ABRA_EARTHQUAKE",
            "05": "ABRA_EARTHQUAKE",
            "06": "ABRA_EARTHQUAKE",
            "07": "ABRA_EARTHQUAKE",
            "08": "ABRA_EARTHQUAKE",
            "09": "ABRA_EARTHQUAKE",
            "10": "ABRA_EARTHQUAKE",
            "11": "ABRA_EARTHQUAKE",
            "12": "ABRA_EARTHQUAKE",
            "13": "ABRA_EARTHQUAKE",
            "14": "ABRA_EARTHQUAKE",
            "15": "ABRA_EARTHQUAKE",
            "16": "ABRA_EARTHQUAKE",
            "17": "ABRA_EARTHQUAKE",
            "18": "ABRA_EARTHQUAKE",
            "19": "ABRA_EARTHQUAKE",
            "20": "ABRA_EARTHQUAKE",
            "21": "ABRA_EARTHQUAKE",
            "22": "ABRA_EARTHQUAKE",
            "23": "ABRA_EARTHQUAKE",
            "24": None,
            "25": None,
            "26": None,
            "27": None,
            "28": None,
            "29": None,
            "30": None,
            "31": None
        },
    }
}