ACTIVE                                  = "ACTIVE"
INACTIVE                                = "INACTIVE"
TD                                      = "TD"
PD                                      = "PD"
PD_DUE_TO_CANCELLATION                  = "PD_DUE_TO_CANCELLATION"
TD_DUE_TO_SUSPENSION                    = "TD_DUE_TO_SUSPENSION"
TD_DUE_TO_COLLECTION_SUSPENSION         = "TD_DUE_TO_COLLECTION_SUSPENSION"
TD_DUE_TO_VOLUNTARY_SUSPENSION          = "TD_DUE_TO_VOLUNTARY_SUSPENSION"
PD_DUE_TO_CHANGE_OWNERSHIP              = "PD_DUE_TO_CHANGE_OWNERSHIP"
PD_DUE_TO_COLLECTION_CANCELLATION       = "PD_DUE_TO_COLLECTION_CANCELLATION"
WIRELESS                                = "wireless"
WIRELINE                                = "wireline"
YES                                     = "YES"
NO                                      = "NO"
OTHERS                                  = "Others"
BANK                                    = "Bank"

LOB_NAME_UKNOWN                         = "Uknown"
LOB_NAME_BUSINESS                       = "Business"
LOB_NAME_BUSINESS_EG                    = "Business EG"
LOB_NAME_BUSINESS_SG                    = "Business SG"
LOB_NAME_PLATINUM_MOBILE                = "Platinum Mobile"
LOB_NAME_PLATINUM_BROADBAND             = "Platinum Broadband"
LOB_NAME_POSTPAID                       = "Postpaid"
LOB_NAME_IN_HOUSE                       = "In House"
LOB_NAME_PREPAID                        = "Prepaid"
LOB_NAME_TRAVELER                       = "Traveler"
LOB_NAME_SHP                            = "SHP"
LOB_NAME_BROADBAND                      = "Broadband"
LOB_NAME_LANDLINE                       = "Landline"
LOB_NAME_PREPAID_HOME_WIFI              = "Prepaid Home Wifi"
LOB_NAME_TM                             = "TM"

GCASH_PLATINUM_FAILED                   = "failed"
GCASH_PLATINUM_IGNORED                  = "ignored"
GCASH_PLATINUM_CONSENTED                = "consented"

IMPACTED                                = "impacted"
IVR_CONNECT                             = "IVR/CONNECT"
LEX                                     = "LEX"
LAST_MILE_ISSUE                         = "account has a last mile issue"

NETWORK_CONCERN_NO_INTERNET             = "I’m experiencing no internet connection"
NETWORK_CONCERN_SLOW_INTERNET           = "I’m experiencing slow internet connection"
NETWORK_CONCERN_NO_LANDLINE             = "I’m experiencing no landline"

GET_NUMBER_NETWORK_CONCERN              = "NETWORK-CONCERN"
GET_NUMBER_LOAD_PROMOS_AND_REWARDS      = "LOAD_PROMOS_AND_REWARDS"
GET_NUMBER_BILLS_AND_PAYMENTS           = "BILLS-AND-PAYMENTS"
GET_NUMBER_MODIFY_OR_TERMINATE          = "MODIFY-OR-TERMINATE"


